name: CI

on:
  push:
  pull_request:

jobs:
  test-minimal-args:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, mac-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - if: ${{ runner.os == 'Windows'}}
      run: choco install cw

    - uses: ./ # Use the action
      with:
        url: https://www.google.com/favicon.ico

    - name: Verify
      run: |
        test -f "favicon.ico" || { echo "File does not exist"; exit 1; }
        file_size=$(cw -c < "favicon.ico")
        test $file_size -ge 1024 || { echo "File size is less than 1KB"; exit 1; }
        echo "File exists and is at least 1KB in size"

  test-with-arg-target:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, mac-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - if: ${{ runner.os == 'Windows'}}
      run: choco install cw

    - uses: ./ # Use the action
      with:
        url: https://www.google.com/favicon.ico
        target: favicon.file

    - name: Verify
      run: |
        test -f "favicon.file" || { echo "File by target name does not exist"; exit 1; }
        file_size=$(cw -c < "favicon.file")
        test $file_size -ge 1024 || { echo "File size is less than 1KB"; exit 1; }
        echo "File exists and is at least 1KB in size"

  test-with-arg-target-in-sub-directory:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, mac-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - if: ${{ runner.os == 'Windows'}}
      run: choco install cw

    - uses: ./ # Use the action
      with:
        url: https://www.google.com/favicon.ico
        target: ./downloads/favicon.file

    - name: Verify
      run: |
        test -f "./downloads" || { echo "Directory downloads does not exist"; exit 1; }
        test -f "./downloads/favicon.file" || { echo "File inside of downloads does not exist"; exit 1; }
        file_size=$(cw -c < "./downloads/favicon.file")
        test $file_size -ge 1024 || { echo "File size is less than 1KB"; exit 1; }
        echo "File exists and is at least 1KB in size"
